config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/list' => 'home#list', as: :list
  get 'home/like' => 'home#like', as: :like
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :posts
  has_many :users, through: :likes
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :posts, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

  def list
    @users = User.all
  end

  def like
    @likes = Like.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<div> 난 footer라고 해 </div>
</br>

app/views/home/_list.html.erb
<%= table_for users do -%>
  <% columns :name, :age, :city %>
<% end %>

app/views/home/_search_bar.html.erb
<%= form_tag "/home/search", method: "get" do %>
  <%= text_field_tag "word" %>
  <%= submit_tag "Strong Serach" %>
<% end %>
</br>

app/views/home/index.html.erb
<div class="container">
  <div id="serah-bar">
    <%= render partial: "search_bar" %>
  </div>
  <div id="list">
    <%= render partial: "list", locals: {users: @users}%>
  </div>
  <div id="footer">
    <%= render partial: "footer" %>
  </div>
</div>

app/views/home/like.html.erb
<div class="container">
  <h3>ORM LIKE <%= link_to "HOME", root_path %> <%= link_to "LIST", list_path  %></h3>
  <table>
    <thead>
      <th>ID</th>
      <th>USER_ID</th>
      <th>POST_ID</th>
      <th>STATUS</th>
    </thead>
    <tbody>
      <% @likes.each do |l| %>
        <tr>
          <td><%= l.id %></td>
          <td><%= l.user_id %></td>
          <td><%= l.post_id %></td>
          <td><%= l.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/list.html.erb
<div class="container">
  <h3>ORM LIST <%= link_to "HOME", root_path %> <%= link_to "LIKE", like_path  %></h3>
  <table>
    <thead>
      <th>ID</th>
      <th>NAME</th>
      <th>AGE</th>
      <th>GENDER</th>
      <th>FOOD</th>
      <th>CITY</th>
    </thead>
    <tbody>
      <% @users.each do |u| %>
        <tr>
          <td><%= u.id %></td>
          <td><%= u.name %></td>
          <td><%= u.age %></td>
          <td><%= u.gender %></td>
          <td><%= u.food %></td>
          <td><%= u.city %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>